server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: dev

  cloud:
    config:
      server:
        git:
          uri: git@github.com:RIN-1011/explorer-config.git
          default-label: main
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            ??...
            -----END OPENSSH PRIVATE KEY-----
          passphrase:
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256

management:
  endpoints:
    web:
      exposure:
        include: refresh, refresh, beans