server:
  port: 8000

spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: api-gateway

    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: auth
          uri: lb://USER
          predicates:
            - Path=/user/auth/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/users/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
    ip-address: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
