server:
  port: 9001

spring:
  application:
    name: realtime
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: explorer
