server:
  port: 9001

spring:
  application:
    name: realtime
  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri : mongodb://ssafy:ssafy@localhost:27017/explorer?authSource=admin