server:
  port: 9000

spring:
  application:
    name: user

  profiles:
    active: dev

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: user

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: localhost
    ip-address: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka