server:
  port: 9000

spring:
  application:
    name: user

  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

---

spring:
  config:
    activate:
      on-profile: prod
    import: "optional:configserver:http://172.26.10.168:8888"

  cloud:
    config:
      uri: http://172.26.10.168:8888
      name: user

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: 172.26.10.168
    hostname: user
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.26.10.168:8761/eureka

---

spring:
  config:
    activate:
      on-profile: dev
    import: "optional:configserver:http://localhost:8888"

  cloud:
    config:
      uri: http://localhost:8888
      name: user

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: localhost
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka